// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ContinuousImprovement.Model
{
    public partial class CipfSuggestion
    {
        public int Id { get; set; }
        public string OwnerSuggestion { get; set; }
        public string OwnerCode { get; set; }
        public string OwnerDept { get; set; }
        public DateTime SubmitDate { get; set; }
        public int IndicatorOfStatus { get; set; }
        public string Status { get; set; }
        public string CurrentStatus { get; set; }
        public string SuggestionAction { get; set; }
        public string ExpectedBenefit { get; set; }
        public string CostCenterRecSug { get; set; }
        public string DeptRecSug { get; set; }
        public string Email { get; set; }
        public DateTime ApproveDt { get; set; }
        public string ApproveSuggBy { get; set; }
        public string OwnerAction { get; set; }
        public DateTime AssignDt { get; set; }
        public DateTime PlanFinishActionDt { get; set; }
        public string ImageUriBefore { get; set; }
        public string ActionDesc { get; set; }
        public string Cifno { get; set; }
        public string SuggestionId { get; set; }
        public string ApproveActionBy { get; set; }
        public string ImageUriAfter { get; set; }
        public string ActionEffectiveness { get; set; }
        public string Remark { get; set; }
        public string InputBy { get; set; }
    }  
}