// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ContinuousImprovement.Model
{
    public partial class CipfListOfLike
    {
        public int Id { get; set; }
        public string SuggestionId { get; set; }
        public string UserName { get; set; }
        public string UserBeLiked { get; set; }
        public DateTime SubmitSuggestionDt { get; set; }
    }
}