// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ContinuousImprovement.Model
{
    public partial class EmployeeInfoCrs530
    {
        public int Id { get; set; }
        public string FullEmployeeId { get; set; }
        public int EmployeeId { get; set; }
        public string FullName { get; set; }
        public string WorkSchedule { get; set; }
        public string CostCenter { get; set; }
        public string Department { get; set; }
        public DateTime Updatetime { get; set; }
    }
}