// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ContinuousImprovement.Model
{
    public partial class HrweeklyReport
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string FullName { get; set; }
        public string CostCenter { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public DateTime JoinDate { get; set; }
        public DateTime WorkingDate { get; set; }
        public string TypeOfDate { get; set; }
        public string Shift { get; set; }
        public string TypeOfLeave { get; set; }
        public decimal DayOfLeave { get; set; }
        public decimal WorkingTimeStandard { get; set; }
        public decimal WorkingDayStandard { get; set; }
        public string EntryTime { get; set; }
        public string OutTime { get; set; }
        public decimal EstOtfirstShift { get; set; }
        public decimal EstOtlastShift { get; set; }
        public decimal OtfirstShift { get; set; }
        public decimal OtlastShift { get; set; }
        public string Week { get; set; }
        public string Month { get; set; }
    }
}