// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ContinuousImprovement.Model
{
    public partial class ProductionDepartment
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public string Tpu { get; set; }
        public string CostCenter { get; set; }
    }
}